### ISSUE TITLE
S3 Access Denied

### ISSUE THREAD

**Issue by zuroh** [ViLab-UCSD/OpenRooms#3]
Hi there, I am in the process of downloading the dataset and have almost completed the downloads but i noticed recently that I was not able to access the s3 download link due to AccessDenied error, may I know how to resolve this? Thank you.

**Comment by lzqsd** [comment]
Hi zuroh,

Sorry for the inconvenience! We recently changed the data sharing links to be from Google drive. The prior S3 link is no longer valid. Please consider downloading from the new links. Thanks!

Best,
Zhengqin
