### ISSUE TITLE
About the view selection for ScanNet RGBD images

### ISSUE THREAD

**Issue by stefan-ainetter** [ViLab-UCSD/OpenRooms#5]
Hi OpenRooms Team,
In the paper in Section 3.4, you state that a specific view selection method is used to determine optimal RGBD images for scenes in ScanNet. Is it possible to provide the information which RGBD image is used for which rendered image, to map the rendered images to the corresponding real images?

Thanks a lot!

**Comment by lzqsd** [comment]
Thanks for the question! I probably replied long ago through email. Currently the camera views used in OpenRooms are different from ScanNet. However, it is possible to map the ScanNet camera poses into OpenRooms coordinate system through a simple transformation defined in Scan2Cad.
